# Generated by Django 5.2 on 2025-09-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_rename_login_login_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogbookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
