# Generated by Django 5.2 on 2025-09-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_logbookdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
